### ISSUE TITLE
2 error

### ISSUE THREAD

**Issue by taslimalimi** [Widiskel/vana-data-hero-bot#1]
1. Status : Error : Failed To Login - 403,
2. Status : Error : To many request-429

**Comment by lsk4205** [comment]
> 1. Status : Error : Failed To Login - 403,
> 2. Status : Error : To many request-429

same

**Comment by Widiskel** [comment]
https://github.com/Widiskel/vana-data-hero-bot?tab=readme-ov-file#console-run-script

check this
