### ISSUE TITLE
store query improvement

### ISSUE THREAD

**Issue by toastyy00** [Widiskel/vana-data-hero-bot#4]
maybe you can simplified process storing query, it's preety taking much time to input query 1 by 1 with name, isn't data on query already have telegram username, use that instead.

**Comment by Widiskel** [comment]
different game different approach. thats the problem if i use that sugestion.
some game only need username or telegram id. but some game need every information from telegram initParams. 

for example if the telegram web apps developer is good. they can use auth date from your param to determinate when your access will be expired, so they need you to store it as a login params to authenticate. 

if you want the faster way then you just need to edit query.txt dirrectly without running bot
