### ISSUE TITLE
Failed to tap

### ISSUE THREAD

**Issue by didiansyah** [Widiskel/vana-data-hero-bot#7]

**Comment by tuanteku9x** [comment]
Game is not problem, I've loged to my phone and tap is fine

**Comment by jerrydao** [comment]
Something is wrong with the tool. Cant tap with tool anymore

**Comment by Widiskel** [comment]
> Game is not problem, I've loged to my phone and tap is fine

you sure ?  try to tapp and refresh it, your point will not increase.
game have daily point limit from tapoing. if it always failed it mean your limit reached.

the game server is dump even if you play it manually

<img width="1112" alt="Screenshot 2024-09-20 at 16 35 28" src="https://github.com/user-attachments/assets/d1420d4c-5690-4f77-9c4e-f5edf3fb5e13">
see this successfully tap.

<img width="386" alt="Screenshot 2024-09-20 at 16 38 29" src="https://github.com/user-attachments/assets/08da8bac-824a-4a87-bfee-1ebd15de80ca">
every request running fine without problem.
if the game server is broken then nothing script can do.
